version: "3"

services:
  django:
    build: .
    container_name: django-docker
    command: bash -c "python manage.py makemigrations app && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      # - CELERY_BROKER=redis://redis:6379/0
      # - CELERY_BACKEND=redis://redis:6379/0

volumes:
  pgdata:
